repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml             # Validate YAML syntax (optionally allowing advanced features)
        args: ["--unsafe"]
      - id: end-of-file-fixer      # Ensure file ends with a newline
      - id: trailing-whitespace    # Remove trailing spaces from lines
      - id: detect-private-key     # Detect accidentally committed private keys
      - id: check-added-large-files # Warn/prevent committing large files
      - id: check-json             # Validate JSON file syntax
      - id: check-toml             # Validate TOML file syntax
      - id: mixed-line-ending      # Normalize line endings (set to LF here)
        args: ["--fix=lf"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets         # Scan code for generic secrets
        exclude: \.ipynb$|.env

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black                  # Auto-format Python code
        args: ["--line-length=120"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.0
    hooks:
      - id: isort                   # Sort Python imports
        args: ["--line-length=120", "--profile=black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8                  # Lint Python for style and common issues
        exclude: scripts/
        args: [--max-line-length=120]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy                   # Perform static type checking on Python code
        exclude: run_agent.py